"""generate_tables

Revision ID: 263c8ab33d4d
Revises: 
Create Date: 2025-09-10 01:19:23.980920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '263c8ab33d4d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('championship',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('chmName', sa.String(), nullable=False),
    sa.Column('dateInit', sa.DateTime(), nullable=False),
    sa.Column('dateEnd', sa.DateTime(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chmName'),
    sa.UniqueConstraint('id')
    )
    op.create_table('combo',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cars', sa.String(), nullable=False),
    sa.Column('circuit', sa.String(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_combo_cars'), 'combo', ['cars'], unique=False)
    op.create_index(op.f('ix_combo_circuit'), 'combo', ['circuit'], unique=False)
    op.create_table('participant',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('prtName', sa.String(), nullable=False),
    sa.Column('alias', sa.String(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alias'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_participant_prtName'), 'participant', ['prtName'], unique=True)
    op.create_table('classification',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('prtId', sa.UUID(), nullable=False),
    sa.Column('chmId', sa.UUID(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chmId'], ['championship.id'], ),
    sa.ForeignKeyConstraint(['prtId'], ['participant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_classification_points'), 'classification', ['points'], unique=False)
    op.create_table('points_system',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('chmId', sa.UUID(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.CheckConstraint('position >= 1 AND position <= 30', name='check_position_range'),
    sa.ForeignKeyConstraint(['chmId'], ['championship.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_points_system_points'), 'points_system', ['points'], unique=False)
    op.create_index(op.f('ix_points_system_position'), 'points_system', ['position'], unique=True)
    op.create_table('race',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('prtId', sa.UUID(), nullable=False),
    sa.Column('chmId', sa.UUID(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chmId'], ['championship.id'], ),
    sa.ForeignKeyConstraint(['prtId'], ['combo.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('result',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('prtId', sa.UUID(), nullable=False),
    sa.Column('racId', sa.UUID(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['prtId'], ['participant.id'], ),
    sa.ForeignKeyConstraint(['racId'], ['race.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_result_position'), 'result', ['position'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_result_position'), table_name='result')
    op.drop_table('result')
    op.drop_table('race')
    op.drop_index(op.f('ix_points_system_position'), table_name='points_system')
    op.drop_index(op.f('ix_points_system_points'), table_name='points_system')
    op.drop_table('points_system')
    op.drop_index(op.f('ix_classification_points'), table_name='classification')
    op.drop_table('classification')
    op.drop_index(op.f('ix_participant_prtName'), table_name='participant')
    op.drop_table('participant')
    op.drop_index(op.f('ix_combo_circuit'), table_name='combo')
    op.drop_index(op.f('ix_combo_cars'), table_name='combo')
    op.drop_table('combo')
    op.drop_table('championship')
    # ### end Alembic commands ###
